// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package handler

import (
	"gorm.io/gorm"
	"zeri/internal/repository"
	"zeri/internal/service"
	"zeri/pkg/cache"
	"zeri/pkg/jwt"
)

// Injectors from wire.go:

func InitializeBaseHandler(db *gorm.DB, cache2 cache.Client, jwt2 jwt.Client) BaseHandler {
	userRepository := repository.NewUserRepository(db)
	menuRepository := repository.NewMuneRepository(db)
	userService := service.NewUserService(userRepository, menuRepository)
	jwtRepository := repository.NewJWTRepository(db)
	jwtService := service.NewJwtService(cache2, jwt2, jwtRepository)
	handlerBaseHandler := NewBaseHandler(userService, jwtService)
	return handlerBaseHandler
}
